"""Database connection configuration (secrets are supplied by environment)."""

from __future__ import annotations

import os
from pathlib import Path

import psycopg2
from psycopg2.extras import RealDictCursor


def _load_local_env():
    """Read a simple backend/.env file without requiring a runtime package."""
    env_file = Path(__file__).with_name(".env")
    if not env_file.is_file():
        return
    for line in env_file.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))


_load_local_env()


def get_connection():
    database_url = os.getenv("DATABASE_URL")
    if database_url:
        return psycopg2.connect(database_url, connect_timeout=5)
    return psycopg2.connect(
        host=os.getenv("DB_HOST", "localhost"),
        port=int(os.getenv("DB_PORT", "5432")),
        user=os.getenv("DB_USER", "postgres"),
        password=os.getenv("DB_PASSWORD", ""),
        dbname=os.getenv("DB_NAME", "planetpulse"),
        connect_timeout=5,
    )


def get_cursor(connection, dictionary=False):
    return connection.cursor(cursor_factory=RealDictCursor if dictionary else None)


def initialize_schema():
    connection = get_connection()
    cursor = get_cursor(connection)
    try:
        cursor.execute("""CREATE TABLE IF NOT EXISTS users (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR(100) NOT NULL,
            email VARCHAR(254) NOT NULL UNIQUE,
            password_hash VARCHAR(255) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        )""")
        cursor.execute("""CREATE TABLE IF NOT EXISTS activities (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            category VARCHAR(32) NOT NULL,
            activity_type VARCHAR(64) NOT NULL,
            value DECIMAL(12,3) NOT NULL,
            unit VARCHAR(16) NOT NULL,
            activity_date DATE NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        )""")
        cursor.execute("""CREATE TABLE IF NOT EXISTS carbon_records (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            activity_id BIGINT NOT NULL UNIQUE REFERENCES activities(id) ON DELETE CASCADE,
            co2e DECIMAL(12,3) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        )""")
        cursor.execute("""CREATE TABLE IF NOT EXISTS user_goals (
            user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            goal_month CHAR(7) NOT NULL,
            target_kg DECIMAL(12,3) NOT NULL DEFAULT 100,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (user_id, goal_month)
        )""")
        cursor.execute("CREATE INDEX IF NOT EXISTS idx_activities_user_date ON activities (user_id, activity_date)")
        connection.commit()
    except Exception:
        connection.rollback()
        raise
    finally:
        cursor.close()
        connection.close()
